
version: 2
jobs:
   build:
     docker:
       - image: continuumio/anaconda3
     steps:
       - checkout
       
       - run: 
            name: run a test script
            command: 
               python3 chicago_map.py
